general:
  mode: verified-acc #For example, if you want to run robustness verification on the ResNet-2B model, changing epsilon from 2/255 (specified in config file) to 1/255:
  complete_verifier: bab
model:
  name: mnist_6_100
  path: models/eran/mnist_6_100_nat.pth
data:
  dataset: MNIST_ERAN_UN
  std: [1.0]
  mean: [0.0]
specification:
  epsilon: 0.026
#attack:
#  pgd_order: after
solver:
  beta-crown:
    batch_size: 8
    iteration: 20
  
bab:
  timeout: 300
  branching:
    method: babsr
    reduceop: max