general:
  mode:  verified-acc
  complete_verifier: bab
model:
  name: mnist_6_100
  path: models/eran/mnist_6_100_nat.pth
data:
  dataset: MNIST_ERAN_UN # No normalization used!
  std: [1.0]
  mean: [0.0]
specification:
  epsilon: 0.026
#attack:
#  pgd_order: after
solver:
  beta-crown:
    batch_size: 64
    iteration: 20
  
bab:
  timeout: 300
  branching:
    method: babsr #sb no implementted
    reduceop: max